### PR TITLE
display error in batch output

### LINKED ISSUE #62: getBatch doesn't report 403 response
# Report

The `getBatch` function hides a 403 response from server.

For example, if the provided token is invalid the API returns a 403 error. However this is not passed through to the output of the `getBatch` function.

Note however that `lookupIp` does throw an error in this case.

# How to reproduce

```
import { IPinfoWrapper } from "node-ipinfo"

const ipinfo = new IPinfoWrapper('malformed token')

await ipinfo.getBatch(['8.8.8.8']) //returns {}
await ipinfo.lookupIp('8.8.8.8') //throws error with the 403 error from the server
```

# Expected behaviour

The `getBatch` function should give some indication that the call has failed (e.g. by throwing an error or including some error data in the returned response).

# Actual behaviour

`getBatch` returns an empty map (i.e. `{}`).

# Impact

Difficult to spot when the passed token value is malformed (because it just looks like the IPs could not be found).

### PR DESCRIPTION
**Pull request by rm-Umar**
fixes #62

### CODE REVIEW

**Review by UmanShahzad — APPROVED** [review]

File: src/ipinfoWrapper.ts [hunk 1]
```diff
@@ -426,29 +426,20 @@ export default class IPinfoWrapper {
...
+                            ipinfo.countryCode = ipinfo.country;
+                            ipinfo.country =
+                                this.countries[ipinfo.countryCode];
+                        }
+                        if (ipinfo.abuse && ipinfo.abuse.country) {
+                            ipinfo.abuse.countryCode = ipinfo.abuse.country;
+                            ipinfo.abuse.country =
+                                this.countries[ipinfo.abuse.countryCode];
                         }
+                        this.cache.set(IPinfoWrapper.cacheKey(key), ipinfo);
```
Comment (UmanShahzad) [inline src/ipinfoWrapper.ts:441]: Actually one thing right here - if `ipinfo.error`, I think we shouldn't cache.
